# Generated by Django 3.2.8 on 2021-12-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(help_text='Digite o estado', max_length=2)),
                ('cidade', models.CharField(help_text='Digite a cidade', max_length=200)),
                ('setor', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome da empresa', max_length=100)),
                ('email', models.EmailField(help_text='Digite o email', max_length=50)),
                ('celular', models.CharField(help_text='Digite o celular (12)345678912', max_length=11)),
                ('endereco', models.CharField(help_text='Digite o endereço (rua e nº)', max_length=200)),
                ('estado', models.CharField(help_text='Digite o estado', max_length=2)),
                ('cidade', models.CharField(help_text='Digite a cidade', max_length=200)),
                ('setor', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
