# Generated by Django 3.2.8 on 2021-12-04 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delphone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Busca',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
