# Generated by Django 3.2.9 on 2021-12-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delphone', '0002_auto_20211202_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuário',
        ),
    ]
